-- Create estimates table for storing sequential estimate numbers and customer data
CREATE TABLE IF NOT EXISTS estimates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    content JSONB NOT NULL, -- Full serialized print data
    customer_info JSONB,    -- Extracted customer info for easy access
    total_price INTEGER NOT NULL
);

-- RLS Policies
ALTER TABLE estimates ENABLE ROW LEVEL SECURITY;

-- Allow insert for authenticated users (staff) or anon (if we want to allow public usage, but usually staff)
-- Assuming this tool is used by staff, but the auth setup in SUPABASE_SETUP.md suggests staff accounts.
-- However, App.tsx seems to use public access or current setup.
-- Let's allow public insert for now based on current usage patterns (likely used by staff on site without strict login in some contexts or anon key is used)
-- If strictly protected:
-- CREATE POLICY "Enable insert for authenticated users only" ON estimates FOR INSERT TO authenticated WITH CHECK (true);
-- For now, consistent with other tables if any, or public:
CREATE POLICY "Enable insert for all users" ON estimates FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all users" ON estimates FOR SELECT USING (true);
